#!/bin/sh

# Set these paths appropriately

BIN="/home/qsypoq/Travaux/memoire-ia-text/treetagger/bin"
CMD="/home/qsypoq/Travaux/memoire-ia-text/treetagger/cmd"
LIB="/home/qsypoq/Travaux/memoire-ia-text/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/belarusian-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/belarusian.par

# do tokenization
$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
