#!/bin/sh

# Set these paths appropriately

BIN="/home/qsypoq/Travaux/memoire-ia-text/treetagger/bin"
CMD="/home/qsypoq/Travaux/memoire-ia-text/treetagger/cmd"
LIB="/home/qsypoq/Travaux/memoire-ia-text/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

